[workspace]
members = [
    "mitsuha-core",
    "mitsuha-runtime",
    "mitsuha-runtime-rpc",
    "mitsuha-wasm-runtime",
    "mitsuha-storage",
    "mitsuha-channel",
    "mitsuha-qflow"
]
