trigger: none

variables:
  - template: templates/build.variables.yml@pipeline-central
  - template: variables/common.variables.yml
  - name: cachePath
    value: $(Pipeline.Workspace)/.cache

resources:
  repositories:
  - repository: pipeline-central
    type: git
    name: Mitsuha/Pipeline-Central
    ref: refs/heads/master

stages:
- stage: 'Build'
  displayName: 'Build Mitsuha Runtime'
  jobs:
  - job: 'Build'
    displayName: 'Build'
    pool:
      vmImage: ubuntu-latest

    steps:
    - template: templates/pipeline.setbuildnumber.yml@pipeline-central
      parameters:
        projectVersion: $(projectVersion)

    - task: CargoAuthenticate@0
      inputs:
        configFile: .cargo/config.toml
      displayName: 'Login to Cargo Artifact Feed'

    - task: Cache@2
      inputs:
        key: 'cargo-test | "$(Agent.OS)" | mitsuha-runtime'
        restoreKeys: |
          cargo-test | "$(Agent.OS)"
          cargo-test
        path: $(cachePath)
      displayName: Cache mitsuha-runtime targets

    - bash: |
        set -e
        sudo apt update
        sudo apt install -y protobuf-compiler
      displayName: 'Install build dependencies'

    - bash: |
        set -e
        export CACHE_DIR=$CACHE_PATH
        make load-cache
        make build
        make cache
      displayName: 'Build'
      env:
        CACHE_PATH: $(cachePath)
